apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.imagecontroller.k8s.io
  # for more information on the below annotation, please see
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: imagecontroller.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                registry:
                  type: string
                repository:
                  type: string
                tag:
                  type: string
                containerfile:
                  type: string
            status:
              type: object
              properties:
                image:
                  type: string
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
  names:
    kind: Image
    plural: images
  scope: Namespaced
