apiVersion: imagecontroller.k8s.io/v1alpha1
kind: Image
metadata:
  name: imagecontroller
spec:
  registry: registry.d.42o.de
  repository: imagecontroller
  tag: latest
  buildArgs:
    - name: ref
      value: 29f547c5
  containerfile: |
    FROM docker.io/library/golang:1.17 as builder
    ARG ref=refs/heads/main
    WORKDIR /usr/src
    ADD https://github.com/discordianfish/k8s-image-controller/archive/${ref}.tar.gz k8s-image-controller.tar.gz
    RUN tar --strip-components=1 -xzvf k8s-image-controller.tar.gz && \
      CGO_ENABLED=0 go install

    FROM scratch
    COPY --from=builder /go/bin/k8s-image-controller /
    ENTRYPOINT [ "/k8s-image-controller" ]
