apiVersion: imagecontroller.5pi.de/v1alpha1
kind: Image
metadata:
  name: my-nginx-image
spec:
  registry: registry.d.42o.de
  repository: test-nginx
  tag: test123
  containerfile: |
    FROM ubuntu:20.04
    RUN set -x && \
        echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/disable-sandbox && \
        apt-get -qy update && \
        apt-get -qy install nginx
    CMD ["nginx", "-g", "daemon off;"]
